import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';
const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between">
        <Header />
        <main className="container m-auto px-4 my-4">{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
