export const data = {
  products: [
    {
      name: 'Combo Bottles',
      slug: 'combo-bottles',
      category: 'Shirts',
      image:
        'https://images.unsplash.com/photo-1664742583396-da58971366a3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 8,
      description: 'A popuar shirt',
    },
    {
      name: 'Math Logics',
      slug: 'math-logics',
      category: 'Galaxy',
      image:
        'https://images.unsplash.com/photo-1664854953181-b12e6dda8b7c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 7,
      description: 'An amazing view of sky in the night',
    },
    {
      name: 'Biscuits',
      slug: 'biscuits',
      category: 'Dairy',
      image:
        'https://images.unsplash.com/photo-1657299156271-d5a435dd65b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
      price: 10,
      brand: 'Blue whales',
      rating: 4.9,
      numReviews: 10,
      countInStock: 5,
      description: 'Most popular dairy product',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image:
        'https://images.unsplash.com/photo-1494253109108-2e30c049369b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popuar shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image:
        'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popuar shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image:
        'https://images.unsplash.com/photo-1664819571553-5687b12d1050?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popuar shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image:
        'https://images.unsplash.com/photo-1664574653006-4d7eb5f1a418?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popuar shirt',
    },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image:
    //     'https://images.unsplash.com/photo-1493612276216-ee3925520721?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image:
    //     'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1539&q=80',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image:
    //     'https://images.unsplash.com/photo-1613336026275-d6d473084e85?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image:
    //     'https://images.unsplash.com/photo-1587590227264-0ac64ce63ce8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image: '/OFF_Overtime_Product_Collections_Large_2X.jpg',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image:
    //     'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 3.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popuar shirt',
    // },
  ],
};
