import Home from '../components/home/Home';
import Layout from '../components/layout/Layout';
import Head from 'next/head';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>{'Homepage - Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  );
}
